import { createUseStyles } from 'react-jss';
import queries from '../../css/queries';

export default createUseStyles({
  logo: {
    margin: '0px',
  },
  logoContainer: {},
  container: {
    marginTop: '-10px',
    backgroundColor: '#1B36A3',
    color: '#FFFFFF',
    position: 'relative',
    overflow: 'hidden',
    '& hr': {
      border: 0,
      height: '1px',
      margin: '20px 0',
      backgroundImage: 'linear-gradient(to left, #1B36A3, #FE5E14, #1B36A3)',
    },
  },
  footCo: {
    '& p': {
      padding: '0px 50px 0px 0px',
    },
  },
  footHead: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'top',
    backgroundColor: '#EBF7FE',
    position: 'relative',
    margin: 0,
    padding: 0,
    height: '400px',
    clipPath: 'polygon(0 0, 100% 0, 100% 50%, 0 100%)',
  },
  pattern1: {
    height: '50px',
    width: '120px',
    position: 'absolute',
    left: 0,
    bottom: 30,
    backgroundColor: '#DFF1FF',
    transform: 'rotate(-8deg)',
  },
  pattern2: {
    height: '50px',
    width: '180px',
    left: 20,
    bottom: 0,
    position: 'absolute',
    border: '1px solid #BCE4FF',
    transform: 'rotate(-8deg)',
  },
  pattern3: {
    height: '50px',
    width: '180px',
    right: 0,
    top: 0,
    marginTop: '-220px',
    marginRight: '-20px',
    position: 'absolute',
    backgroundColor: '#00E1FF',
    transform: 'rotate(-8deg)',
    zIndex: 1000,
  },
  footHeadContent: {
    width: '50%',
    color: '#000',
    textAlign: 'center',
    padding: '50px 0 50px 0',
    zIndex: 100,
    [queries.m]: {
      width: '80%',
    },
    '& h2': {
      fontSize: '36px',
      fontWeight: 'bold',
      fontFamily: 'DM sans',
    },
  },
  main: {
    position: 'relative',
  },
  text: {
    display: 'inline-block',
  },
  heroButton1: {
    backgroundImage: 'linear-gradient(#9F3CD7, #BC47DD)',
    border: 0,
    borderRadius: '4px',
    boxShadow: 'rgba(0, 0, 0, .3) 0 5px 15px',
    boxSizing: 'border-box',
    color: '#fff',
    cursor: 'pointer',
    fontFamily: 'Montserrat,sans-serif',
    fontSize: '.9em',
    margin: '5px',
    padding: '10px 15px',
    textAlign: 'center',
    userSelect: 'none',
    touchAction: 'manipulation',
  },
  copyright: {
    textAlign: 'center',
    fontSize: '18px',
    paddingBottom: '20px',
  },
  '@media screen and (max-width: 1024px)': {
    footHead: {
      display: 'flex',
      justifyContent: 'center',
      alignItems: 'top',
      backgroundColor: '#EBF7FE',
      position: 'relative',
      margin: 0,
      paddingBottom: '100px',
      height: '600px',
      clipPath: 'polygon(0 0, 100% 0, 100% 70%, 0 100%)',
    },
    pattern1: {
      height: '50px',
      width: '120px',
      position: 'absolute',
      left: 0,
      bottom: 30,
      backgroundColor: '#DFF1FF',
      transform: 'rotate(-25deg)',
    },
    pattern2: {
      height: '50px',
      width: '180px',
      left: 20,
      bottom: 0,
      position: 'absolute',
      border: '1px solid #BCE4FF',
      transform: 'rotate(-25deg)',
    },
    pattern3: {
      height: '50px',
      width: '180px',
      right: 0,
      top: 0,
      marginTop: '500px',
      marginRight: '-20px',
      position: 'absolute',
      backgroundColor: '#00E1FF',
      transform: 'rotate(-25deg)',
      zIndex: 1000,
    },
    logoContainer: {
      display: 'flex',
      justifyContent: 'center',
      width: '100%',
    },
    logo: {
      width: '150px',
      height: '40px',
    },
    text: {
      textAlign: 'center',
    },
  },
});
